### ISSUE TITLE
Rename Profiles to Profile Groups 

### ISSUE THREAD

**Issue by afrold** [usnistgov/gvt-ui#12]

**Comment by ncrouzier-nist** [comment]
@haffonist 
Where is this change needed?

**Comment by afrold** [comment]
In the nav tree on the left side.

**Comment by afrold** [comment]
Actually, this should be done on hit-base-tool. May be it is already done.



Harold Affo

--------------------------------------------------------------------
The contents of this e-mail and any attachments are intended solely for the use
of the named addressee(s) and may contain confidential and/or privileged
information. Any unauthorized use, copying, disclosure, or distribution of the
contents of this e-mail is strictly prohibited. If you are not the intended
recipient, please notify the sender immediately and delete this email. Thank you.


________________________________

**Comment by ncrouzier-nist** [comment]
It's not in the base-tool (yet).
Are we sure we want Profile Groups? We are displaying both Groups and Profiles in this tree...
