### ISSUE TITLE
Add profile verificaiton tab

### ISSUE THREAD

**Issue by afrold** [usnistgov/gvt-ui#17]
Add a new tab called 'Profile Validation'
Support:
- Uploading profile xml 
- Uploading valuesets xml 
- Upload constraints xml 

Validation will display the report generated by profile-validation module located at 
https://github.com/usnistgov/hl7-profile-validation

**Comment by ncrouzier-nist** [comment]
is this just for GVT or the base tool?

**Comment by afrold** [comment]
just gvt


Harold Affo

--------------------------------------------------------------------
The contents of this e-mail and any attachments are intended solely for the use
of the named addressee(s) and may contain confidential and/or privileged
information. Any unauthorized use, copying, disclosure, or distribution of the
contents of this e-mail is strictly prohibited. If you are not the intended
recipient, please notify the sender immediately and delete this email. Thank you.


________________________________
