### ISSUE TITLE
 There is no Download button for the Test   Story, Test Data Specification, and Message Content

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/gvt-ui#19]
In GVT, there is no Download button for the Test   Story, Test Data Specification, and Message Content tabs from the   Test Step Test Selection or Test Execution screens; only the Example   Message tab has a Download button.
--
 
![image](https://user-images.githubusercontent.com/14842422/39371244-1b0d99c8-4a0f-11e8-8f3d-5065a0be6642.png)

 
 
In IZ, there is a Download button for the Test   Story, Test Data Specification, Message Content, and Example Message   tabs from the Test Step Test Selection and Test Execution screens.
 
 
![image](https://user-images.githubusercontent.com/14842422/39371259-2182d066-4a0f-11e8-8396-ebd6ca191257.png)

**Comment by ncrouzier-nist** [comment]
All artifacts can now be downloaded
