### ISSUE TITLE
Display datatypes options for OBX-5 dynamic mapping

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/gvt-ui#27]
Would be great to see the datatypes options for varies fields such as OBX-5

**Comment by ncrouzier-nist** [comment]
Would displaying them in the popup while you hover over "varies" be enough?

**Comment by ncrouzier-nist** [comment]
Fixed datatype options display for "varies DT" when the name is other than "varies".
Now works for all variation of DT name containing "var"
