### ISSUE TITLE
Reported Issue - TCs gone after reboot

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/gvt-ui#5]
Test cases completely gone after a reboot.

**Comment by ncrouzier-nist** [comment]
Context free or context based?
Is this issue from before or after we reset the database on Thursday?

**Comment by smartinez290** [comment]
Context Free. I think it was after the reset.

**Comment by ncrouzier-nist** [comment]
All of them are gone?
Uploaded from file or through IGAMT?

**Comment by smartinez290** [comment]
I reloaded them again after. I am not 100% sure it was after the reset.

**Comment by ncrouzier-nist** [comment]
Close until we have clear evidences TCs are disappearing.

**Comment by afrold** [comment]
Agree. But I am reopening and moving it to pending instead of closing it.

**Comment by smartinez290** [comment]
Did you do something? The TCs are gone. 
![tcsgone](https://cloud.githubusercontent.com/assets/14842422/26070520/fb3aaa9e-3972-11e7-8be2-318a8bbdc080.png)

**Comment by ncrouzier-nist** [comment]
LOG IN!
